"""create_all_tables_with_indexes

Revision ID: cf547709947f
Revises: 001_initial
Create Date: 2026-04-03 22:20:23.122633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf547709947f'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interest_forms', sa.Column('email', sa.String(), nullable=True))
    op.add_column('interest_forms', sa.Column('message', sa.Text(), nullable=True))
    op.add_column('interest_forms', sa.Column('status', sa.String(), nullable=True))
    op.add_column('interest_forms', sa.Column('contact_date', sa.DateTime(), nullable=True))
    op.add_column('interest_forms', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('interest_forms', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('interest_forms', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('interest_forms', 'pet_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_interest_forms_created_at'), 'interest_forms', ['created_at'], unique=False)
    op.create_index(op.f('ix_interest_forms_email'), 'interest_forms', ['email'], unique=False)
    op.create_index('ix_interest_forms_pet_created', 'interest_forms', ['pet_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_interest_forms_pet_id'), 'interest_forms', ['pet_id'], unique=False)
    op.create_index(op.f('ix_interest_forms_phone'), 'interest_forms', ['phone'], unique=False)
    op.create_index(op.f('ix_interest_forms_status'), 'interest_forms', ['status'], unique=False)
    op.create_index('ix_interest_forms_status_created', 'interest_forms', ['status', 'created_at'], unique=False)
    op.create_index('ix_interest_forms_user_created', 'interest_forms', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_interest_forms_user_id'), 'interest_forms', ['user_id'], unique=False)
    op.create_index('ix_interest_forms_user_pet', 'interest_forms', ['user_id', 'pet_id'], unique=False)
    op.drop_constraint('interest_forms_pet_id_fkey', 'interest_forms', type_='foreignkey')
    op.drop_constraint('interest_forms_user_id_fkey', 'interest_forms', type_='foreignkey')
    op.create_foreign_key(None, 'interest_forms', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'interest_forms', 'pets', ['pet_id'], ['id'], ondelete='CASCADE')
    op.add_column('organizations', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('organizations', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('organizations', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('organizations', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_organizations_created_at'), 'organizations', ['created_at'], unique=False)
    op.create_index('ix_organizations_name_owner', 'organizations', ['name', 'owner_id'], unique=False)
    op.create_index('ix_organizations_owner_created', 'organizations', ['owner_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_organizations_owner_id'), 'organizations', ['owner_id'], unique=False)
    op.drop_constraint('organizations_owner_id_fkey', 'organizations', type_='foreignkey')
    op.create_foreign_key(None, 'organizations', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.alter_column('pets', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index('idx_organization_created', 'pets', ['organization_id', 'created_at'], unique=False)
    op.create_index('idx_organization_type', 'pets', ['organization_id', 'pet_type'], unique=False)
    op.create_index('idx_type_created', 'pets', ['pet_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_pets_created_at'), 'pets', ['created_at'], unique=False)
    op.create_index(op.f('ix_pets_organization_id'), 'pets', ['organization_id'], unique=False)
    op.create_index(op.f('ix_pets_pet_type'), 'pets', ['pet_type'], unique=False)
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index('ix_users_active_created', 'users', ['is_active', 'created_at'], unique=False)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index('ix_users_email_active', 'users', ['email', 'is_active'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index('ix_users_email_active', table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index('ix_users_active_created', table_name='users')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'updated_at')
    op.drop_index(op.f('ix_pets_pet_type'), table_name='pets')
    op.drop_index(op.f('ix_pets_organization_id'), table_name='pets')
    op.drop_index(op.f('ix_pets_created_at'), table_name='pets')
    op.drop_index('idx_type_created', table_name='pets')
    op.drop_index('idx_organization_type', table_name='pets')
    op.drop_index('idx_organization_created', table_name='pets')
    op.alter_column('pets', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'organizations', type_='foreignkey')
    op.create_foreign_key('organizations_owner_id_fkey', 'organizations', 'users', ['owner_id'], ['id'])
    op.drop_index(op.f('ix_organizations_owner_id'), table_name='organizations')
    op.drop_index('ix_organizations_owner_created', table_name='organizations')
    op.drop_index('ix_organizations_name_owner', table_name='organizations')
    op.drop_index(op.f('ix_organizations_created_at'), table_name='organizations')
    op.alter_column('organizations', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('organizations', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('organizations', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('organizations', 'updated_at')
    op.drop_constraint(None, 'interest_forms', type_='foreignkey')
    op.drop_constraint(None, 'interest_forms', type_='foreignkey')
    op.create_foreign_key('interest_forms_user_id_fkey', 'interest_forms', 'users', ['user_id'], ['id'])
    op.create_foreign_key('interest_forms_pet_id_fkey', 'interest_forms', 'pets', ['pet_id'], ['id'])
    op.drop_index('ix_interest_forms_user_pet', table_name='interest_forms')
    op.drop_index(op.f('ix_interest_forms_user_id'), table_name='interest_forms')
    op.drop_index('ix_interest_forms_user_created', table_name='interest_forms')
    op.drop_index('ix_interest_forms_status_created', table_name='interest_forms')
    op.drop_index(op.f('ix_interest_forms_status'), table_name='interest_forms')
    op.drop_index(op.f('ix_interest_forms_phone'), table_name='interest_forms')
    op.drop_index(op.f('ix_interest_forms_pet_id'), table_name='interest_forms')
    op.drop_index('ix_interest_forms_pet_created', table_name='interest_forms')
    op.drop_index(op.f('ix_interest_forms_email'), table_name='interest_forms')
    op.drop_index(op.f('ix_interest_forms_created_at'), table_name='interest_forms')
    op.alter_column('interest_forms', 'pet_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('interest_forms', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('interest_forms', 'updated_at')
    op.drop_column('interest_forms', 'notes')
    op.drop_column('interest_forms', 'contact_date')
    op.drop_column('interest_forms', 'status')
    op.drop_column('interest_forms', 'message')
    op.drop_column('interest_forms', 'email')
    # ### end Alembic commands ###
